version: "3"

services:
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - '/home/USER/rabbitmq/:/var/lib/rabbitmq'
    hostname: "localhost"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq

  zuul-gateway:
    build: ./zuulgateway
    container_name: zuul-gateway
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - CAMPAIGN_SERVICE_HOST=${CAMPAIGN_SERVICE_HOST}
      - EMAIL_SERVICE_HOST=${EMAIL_SERVICE_HOST}
      - CONFIRMATION_TOKEN_SERVICE_HOST=${CONFIRMATION_TOKEN_SERVICE_HOST}
      - PERMISSION_SERVICE_HOST=${PERMISSION_SERVICE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${ZUUL_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - rabbitmq

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${USER_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - eureka-server
      - rabbitmq

  campaign-service:
    build: ./campaign-service
    container_name: campaign-service
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${CAMPAIGN_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - eureka-server
      - rabbitmq

  email-service:
    build: ./email-service
    container_name: email-service
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${EMAIL_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - eureka-server
      - rabbitmq

  confirmation-token-service:
    build: ./confirmation-token-service
    container_name: confirmation-token-service
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${CONFIRMATION_TOKEN_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - eureka-server
      - rabbitmq

  permissions-service:
    build: ./permissions-service
    container_name: permissions-service
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${PERMISSIONS_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - eureka-server
      - rabbitmq

  #Postgres configuration
  matrix-postgres:
    image: "postgres:13.0-alpine"
    container_name: matrix-postgres
    volumes:
      - matrix-data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${ALL_DATABASES}
    ports:
      - "5432:5432"
    restart: unless-stopped

  #pgAdmin configuration
  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - matrix-postgres
    ports:
      - "5555:80"
    restart: unless-stopped

#Volumes for DB data
volumes:
  matrix-data:
  pgadmin-data:
