version: "3"

services:
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - '/home/USER/rabbitmq/:/var/lib/rabbitmq'
    hostname: "localhost"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - matrix-postgres
    restart: on-failure

  zuul-gateway:
    build: ./zuulgateway
    container_name: zuul-gateway
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - CAMPAIGN_SERVICE_HOST=${CAMPAIGN_SERVICE_HOST}
      - EMAIL_SERVICE_HOST=${EMAIL_SERVICE_HOST}
      - CONFIRMATION_TOKEN_SERVICE_HOST=${CONFIRMATION_TOKEN_SERVICE_HOST}
      - PERMISSION_SERVICE_HOST=${PERMISSION_SERVICE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${ZUUL_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - rabbitmq
      - matrix-postgres
    restart: on-failure

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${USER_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - eureka-server
      - rabbitmq
      - matrix-postgres
    restart: on-failure

  campaign-service:
    build: ./campaign-service
    container_name: campaign-service
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${CAMPAIGN_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - eureka-server
      - rabbitmq
      - matrix-postgres
    restart: on-failure

  email-service:
    build: ./email-service
    container_name: email-service
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${EMAIL_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - eureka-server
      - rabbitmq
      - matrix-postgres
    restart: on-failure

  confirmation-token-service:
    build: ./confirmation-token-service
    container_name: confirmation-token-service
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${CONFIRMATION_TOKEN_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - eureka-server
      - rabbitmq
      - matrix-postgres
    restart: on-failure

  permission-service:
    build: ./permission-service
    container_name: permission-service
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${PERMISSION_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - eureka-server
      - rabbitmq
      - matrix-postgres
    restart: on-failure

  #Postgres configuration
  matrix-postgres:
    image: "postgres:13.0-alpine"
    container_name: matrix-postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - matrix-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${ALL_DATABASES}
    ports:
      - "5432:5432"
    restart: unless-stopped

  #pgAdmin configuration
  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - matrix-postgres
    ports:
      - "5555:80"
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - zuul-gateway
    environment:
      - CHOKIDAR_USEPOLLING=true
#Volumes for DB data
volumes:
  pgadmin-data:
  matrix-data: