# Application name configuration for Eureka
spring:
  application:
    name: product

# Application port configuration
server:
  port: 8082

# Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
