# Application name configuration for Eureka
spring:
  application:
    name: user-service

# Database configuration
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
jooq:
  sql-dialect: Postgres

# Application server port
server:
  port: 8081
  error:
    include-message: always