# Application name configuration for Eureka
spring:
  application:
    name: gateway

# Server port configuration
server:
  port: 8080

# Zuul configuration
zuul:
  routes:
    product:
      url: http://product-service:8082/

# Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
