# Application name configuration for Eureka
spring:
  application:
    name: gateway

# Server port configuration
server:
  port: 8080

# Zuul configuration
zuul:
  routes:
    product:
      url: http://${CAMPAIGN_SERVICE_HOST:localhost}:8082/
  sensitive-headers: Cookie,Set-Cookie

# Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

# Database credentials
data:
  datasource:
    jdbc-url: jdbc:postgresql://matrix-postgres:5432/campaigndb
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool-size: 30
